version: "3"
services:
  geth:
    image: ethereum/client-go:v1.10.26
    ports:
      - "8545:8545"
    command: >
      --miner.gaslimit 12000000
      --http --http.api personal,eth,net,web3,debug
      --http.vhosts '*,localhost,host.docker.internal' --http.addr "0.0.0.0"
      --ignore-legacy-receipts --allow-insecure-unlock --rpc.allow-unprotected-txs
      --dev
      --verbosity 2
      --nodiscover --maxpeers 0 --mine --miner.threads 1
      --networkid 1337

  bundler:
    image: bundler-typescript
    ports:
      - "3001:3001"
    environment:
      - BENEFICIARY=0x3c812AFCf93C73338fC31d1769AD1071Ea982E7d
      - MNEMONIC=test test test test test test test test test test test junk
    command: >
      --port 3001
      --network http://localhost:8545
      --txMode private