version: "3"
services:
  bundler-relayer:
    depends_on:
      bundler-builder:
        condition: service_started
    container_name: bundler-relayer-dev
    image: bundler-relayer:v-local
    ports:
      - "4337:4337"
    env_file:
      - ./packages/bundler-relayer/.env
    command: >
      --port 4337
      --network http://host.docker.internal:8545
      --bundlerBuilder http://host.docker.internal:4338/rpc
      --debug

  bundler-builder:
    container_name: bundler-builder-dev
    image: bundler-builder:v-local
    ports:
      - "4338:4338"
    env_file:
      - ./packages/bundler-builder/.env
    command: >
      --port 4338
      --network http://host.docker.internal:8545
      --txMode base

  influxdb:
    container_name: influxdb
    image: influxdb:2.7.1
    ports:
      - "8086:8086"
    command: >
      --reporting-disabled
    volumes:
      - ./influxdb-data:/var/lib/influxdb2

  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./grafana-data:/var/lib/grafana
volumes:
  grafana-data: {}