name: compliance

on:
  workflow_dispatch:

jobs:
  compliance:
    name: compliance
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Setup PDM
        run: curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -

      - name: Setup NodeJS
        uses: "actions/setup-node@v3"
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Checkout bundler spec tests
        uses: actions/checkout@v3
        with:
          repository: eth-infinitism/bundler-spec-tests
          ref: master
          path: ./bundler-spec-tests
          submodules: true

      - name: Setup bundler spec tests
        working-directory: ./bundler-spec-tests
        run: pdm install && pdm run update-deps

      - name: Install Geth
        run: |
          sudo add-apt-repository -y ppa:ethereum/ethereum && \
          sudo apt-get update && \
          sudo apt-get install ethereum

      - name: Run Geth
        run: |
          geth \
          --verbosity 1 \
          --http.vhosts '*,localhost,host.docker.internal' \
          --http \
          --http.api eth,net,web3,debug \
          --http.corsdomain '*' \
          --http.addr "0.0.0.0" \
          --nodiscover --maxpeers 0 --mine \
          --networkid 1337 \
          --dev \
          --allow-insecure-unlock \
          --rpc.allow-unprotected-txs \
          --dev.gaslimit 20000000 &

      - name: Deploy ERC-4337 contracts
        working-directory: ./bundler-spec-tests
        # checkout to v0.6.0  https://github.com/eth-infinitism/account-abstraction
        run: |
          cd @account-abstraction && \
          git fetch --tags origin && \
          git checkout v0.6.0 && \
          yarn deploy --network localhost

      - name: Fund bundler
        run: |
          geth \
          --exec "eth.sendTransaction({from: eth.accounts[0], to: \"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266\", value: web3.toWei(4337, \"ether\")})" \
          attach http://localhost:8545/

      - name: Install Transeptor deps
        run: npm install --no-package-lock

      - name: Install Transeptor build tool deps
        run: npm install --save-dev @nx/nx-linux-x64-gnu

      - name: Build Transeptor
        run: npm run build

      - name: Setup Configuration for Transeptor
        run: chmod +x ./scripts/compliance_test.sh

      - name: Start Transeptor
        run: nohup ./scripts/compliance_test.sh &

      - name: Run tests
        working-directory: ./bundler-spec-tests
        run: pdm run pytest -rA -W ignore::DeprecationWarning --url http://127.0.0.1:4000/rpc/ --entry-point 0x0000000071727De22E5E9d8BAf0edAc6f37da032 --ethereum-node http://localhost:8545
