name: Publish Release transeptor docker images

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get package version
        id: get_version
        run: echo version=$(node -p "require('./package.json').version") >> $GITHUB_OUTPUT
      - name: Build and push Docker image(Relayer)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile.bundler-relayer
          push: true
          tags: |
            transeptorlabs/bundler-relayer:${{ steps.get_version.outputs.version }}
            transeptorlabs/bundler-relayer:latest
      - name: Build and push Docker image(Builder)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile.bundler-builder
          push: true
          tags: |
            transeptorlabs/bundler-builder:${{ steps.get_version.outputs.version }}
            transeptorlabs/bundler-builder:latest
