version: "3"
services:
  geth:
    container_name: geth
    image: ethereum/client-go:v1.10.26
    ports:
      - "8545:8545"
    command: >
      --miner.gaslimit 12000000
      --dev.gaslimit 20000000
      --http 
      --http.api personal,eth,net,web3,debug
      --http.vhosts '*,localhost,host.docker.internal' 
      --http.addr "0.0.0.0"
      --ignore-legacy-receipts 
      --allow-insecure-unlock 
      --rpc.allow-unprotected-txs
      --dev
      --verbosity 2
      --nodiscover 
      --maxpeers 0 
      --mine 
      --miner.threads 1
      --networkid 1337

  bundler-typescript-local:
    container_name: transeptor
    image: bundler-typescript:v-local
    ports:
      - "4000:4000"
    env_file:
      - ../../.env
    depends_on:
      - geth
    command: >
      --port 4000
      --network http://host.docker.internal:8545
      --txMode base
      --httpApi web3,eth,debug

  influxdb:
    container_name: influxdb
    image: influxdb:2.7.1
    ports:
      - "8086:8086"
    command: >
      --reporting-disabled
    volumes:
      - ../../influxdb-data:/var/lib/influxdb2

  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ../../grafana-data:/var/lib/grafana

  erigon:
    container_name: erigon
    image: thorax/erigon:2.54.0-arm64
    ports: [ "8545:8545" ]
    command: >
      --datadir=dev
      --chain=dev 
      --private.api.addr=localhost:9090 
      --nodiscover 
      --maxpeers 0 
      --mine
      --http.corsdomain="*"
      --http.api=eth,erigon,web3,net,debug,trace,txpool,parity,admin
      --allow-insecure-unlock 
      --networkid 1337
      --http.vhosts '*,localhost,host.docker.internal' 
      --http.addr "0.0.0.0"
      --http
      --miner.gaslimit 12000000   
volumes:
  grafana-data: {}